language: node_js
node_js:
 - "10"
os:
 - linux

stages:
 - test
 - name: deploy
   if: tag =~ ^v

jobs:
 include:
   - stage: test
     script:
       - npm install -g eslint babel-eslint eslint-plugin-import eslint-plugin-react eslint-plugin-react-native
       - eslint src
   - stage: deploy
     deploy:
       provider: npm
       email: summer88123@163.com
       api_key: "$NPM_TOKEN"
       on:
         tags: true
